export const STORE_TYPE = "main"
export const SAVE = `${STORE_TYPE}/SAVE`
export const EDIT = `${STORE_TYPE}/EDIT`
export const DELETE_DATA = `${STORE_TYPE}/DELETE_DATA`
// export const LOGOUT = `${STORE_TYPE}/LOGOUT`
// export const LOGIN_SUCCESS = `${STORE_TYPE}/LOGIN_SUCCESS`
// export const LOGIN_FAILURE = `${STORE_TYPE}/LOGIN_FAILURE`
// export const CHECK_IS_LOGIN = `${STORE_TYPE}/CHECK_IS_LOGIN`
// export const LOGIN_ERROR_RESET = `${STORE_TYPE}/LOGIN_ERROR_RESET`
